// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ctesp2022_final_gg.Database;

namespace ctesp2022_final_gg.Migrations
{
    [DbContext(typeof(BankContext))]
    partial class BankContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ctesp2022_final_gg.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Contacto")
                        .HasColumnType("int");

                    b.Property<string>("Morada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCliente")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("ctesp2022_final_gg.ContaBancaria", b =>
                {
                    b.Property<int>("ContaBancariaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("IBAN")
                        .HasColumnType("int");

                    b.Property<int>("NumeroConta")
                        .HasColumnType("int");

                    b.Property<double>("SaldoCorrente")
                        .HasColumnType("float");

                    b.HasKey("ContaBancariaId");

                    b.HasIndex("ClienteId");

                    b.ToTable("ContaBancaria");
                });

            modelBuilder.Entity("ctesp2022_final_gg.TipoTransacao", b =>
                {
                    b.Property<int>("TipoTransacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomeTipoTransacao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoTransacaoId");

                    b.ToTable("TipoTransacao");
                });

            modelBuilder.Entity("ctesp2022_final_gg.Transacao", b =>
                {
                    b.Property<int>("TransacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ContaBancariaId")
                        .HasColumnType("int");

                    b.Property<int>("ContaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Dia")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoTransacaoId")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("TransacaoId");

                    b.HasIndex("ContaBancariaId");

                    b.HasIndex("TipoTransacaoId");

                    b.ToTable("Transacao");
                });

            modelBuilder.Entity("ctesp2022_final_gg.ContaBancaria", b =>
                {
                    b.HasOne("ctesp2022_final_gg.Cliente", "Cliente")
                        .WithMany("ContaBancarias")
                        .HasForeignKey("ClienteId");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ctesp2022_final_gg.Transacao", b =>
                {
                    b.HasOne("ctesp2022_final_gg.ContaBancaria", "ContaBancaria")
                        .WithMany("Transacoes")
                        .HasForeignKey("ContaBancariaId");

                    b.HasOne("ctesp2022_final_gg.TipoTransacao", "TipoTransacao")
                        .WithMany()
                        .HasForeignKey("TipoTransacaoId");

                    b.Navigation("ContaBancaria");

                    b.Navigation("TipoTransacao");
                });

            modelBuilder.Entity("ctesp2022_final_gg.Cliente", b =>
                {
                    b.Navigation("ContaBancarias");
                });

            modelBuilder.Entity("ctesp2022_final_gg.ContaBancaria", b =>
                {
                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
